version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      - DB_HOST=postgresql
      - DB_PASSWORD=abc123
    volumes:
      - ./:/code
    ports:
      - "5005:80"
  db:
    container_name: postgresql
    image: postgres:latest
    restart: always
    networks:
      - allocation
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: allocation
      POSTGRES_PASSWORD: abc123
      POSTGRES_DB: allocation
      POSTGRES_INITDB_ARGS: --auth=scram-sha-256
    ports:
      - "54321:5432"
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    networks:
      - allocation
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"

networks:
  allocation: