version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - allocation
    depends_on:
      - postgresql
    environment:
      - DB_HOST=postgresql
      - DB_PASSWORD=abc123
    volumes:
      - ./:/code
    ports:
      - "5005:80"
  postgresql:
    image: postgres:13.4-alpine
    networks:
      - allocation
    environment:
      POSTGRES_USER: allocation
      POSTGRES_PASSWORD: abc123
      POSTGRES_DB: allocation
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    networks:
      - allocation
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"

networks:
  allocation: