version: '3.8'

services:

  redis_pubsub:
    build:
      context: .
      dockerfile: Dockerfile
    image: allocation-image
    networks:
      - allocation
    depends_on:
      - postgresql
      - redis
    environment:
      - DB_HOST=postgres
      - DB_PASSWORD=abc123
      - REDIS_HOST=redis
      - EMAIL_host=mailhog
      - PYTHONDONTWRITEBYTECODE=1
    volumes:
      - ./src:/src
      - ./tests:/tests
    entrypoint:
      - python
      - /src/allocation/entrypoints/redis_eventconsumer.py

  api:
    image: allocation-image
    networks:
      - allocation
    depends_on:
      - redis_pubsub
      - mailhog
    environment:
      - DB_HOST=postgresql
      - DB_PASSWORD=abc123
      - API_HOST=api
      - REDIS_HOST=redis
      - EMAIL_HOST=mailhog
      - PYTHONDONTWRITEBYTECODE=1
      - FLASK_APP=allocation/entrypoints/flask_app.py
      - FLASK_DEBUG=1
      - PYTHONUNBUFFERED=1
    volumes:
      - ./src:/src
      - ./tests:/tests
    entrypoint:
      - flask
      - run
      - --host=0.0.0.0
      - --port=80
    ports:
      - "5005:80"

  postgresql:
    image: postgres:13.4-alpine
    networks:
      - allocation
    environment:
      POSTGRES_USER: allocation
      POSTGRES_PASSWORD: abc123
      POSTGRES_DB: allocation
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "54321:5432"

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    networks:
      - allocation
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"

  redis:
    image: redis:alpine
    networks:
      - allocation
    ports:
      - "63791:6379"

  mailhog:
    image: mailhog/mailhog
    networks:
        - allocation
    ports:
      - "11025:1025"
      - "18025:8025"

networks:
  allocation: